---
output: 
  flexdashboard::flex_dashboard:
    css: !expr eurostatRTool::css()
    orientation: rows
    vertical_layout: fill
    logo: !expr eurostatRTool::logo()
    includes:
      in_header: !expr eurostatRTool::social()
      after_body: !expr eurostatRTool::footer()
    self_contained: false
    mathjax: null
    encoding: UTF-8
params:
  data: data
  geo_labels: geo_labels
  menu_categories: menu_categories
  dashboard_structure_data: dashboard_structure_data
  title: title
  edition: edition
  value_boxes: value_boxes
  colors_palette: colors_palette
  bar_chart_colors_palette: bar_chart_colors_palette
  overview_text: overview_text
  latest_changes_summary: latest_changes_summary
  dropdown_menu: dropdown_menu
  pdf_reports: pdf_reports
  meta_description: meta_description
title: "`r params$title`"
author: "`r params$edition`"
---

<script>
$('.navbar-logo').wrap('<a href=`r logo_link()` target="_blank">');
</script>

<script defer src="https://europa.eu/webtools/load.js" type="text/javascript"></script>

<script type="application/json">
{
   "utility" : "analytics",
    "siteID" : 59,
    "sitePath" : ["ec.europa.eu\/eurostat"],
    "is404" : false
}
</script>

```{r}
# Add the meta description for SEO
metathis::meta() %>% 
  metathis::meta_description(meta_description)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Overview {#overview}
===

Column {.overview-col}
---------------------------------------------------------------------

```{r render value boxes, include=FALSE}
# Create variable which stores all subpages outputs
vb_out = NULL
  
# Set knitr options to allow duplicate labels (needed for the subpages)
options(knitr.duplicate.label = 'allow')
  
# Create temporary environment which we use for knitting valuebox_subpages.RMD 
valuebox_subpage_env <- new.env()
if (!is.null(value_boxes)) {  
  for (i in 1:nrow(value_boxes)) {
    # Filter value_boxes
    valuebox_data <- value_boxes[i,]
    
    # Assign valuebox data and index to valuebox_subpage_env
    assign("valuebox_data", valuebox_data, valuebox_subpage_env)
    assign("valuebox_index", i, valuebox_subpage_env)
    
    # Knit valuebox_subpage.RMD using the valuebox_subpage_env and add result to out vector
    vb_out = c(vb_out, knitr::knit_child('valuebox_subpage.RMD', envir = valuebox_subpage_env))
  }
}
```

`r if (!is.null(vb_out)) {paste(knitr::knit_child(text = vb_out), collapse = '')}`

Column {.overview-col}
---------------------------------------------------------------------

`r if (!is.null(overview_text)) { paste0('<p id="overview-text">', overview_text, '</p>') }`

`r if (!is.null(latest_changes_summary)) { paste0('<p id="latest-changes-summary">', latest_changes_summary, '</p>') }`

```{r render menu, include=FALSE}
# Read if dropdown menu is enabled, else use storyboard layout
if (dropdown_menu) {
  subpage <- "dropdown_menu_subpage.RMD"
} else {
  subpage <- "menu_subpage.RMD"
}

# Create variable which stores all subpages outputs
out = NULL

# Set knitr options to allow duplicate labels (needed for the subpages)
options(knitr.duplicate.label = 'allow')

# Create temporary environment which we use for knitting menu_subpages.RMD 
menu_subpage_env <- new.env()

menu_cat <- intersect(unique(dashboard_structure_data$menu_position), 1:length(menu_categories))

for (i in menu_cat) {
  # Filter structure data for menu category
  menu_subpage_data <- dashboard_structure_data %>% 
    dplyr::filter(menu_position == i)
  
  # Assign data, geo labels, colors palettes, filtered structure data and menu
  # category to menu_subpage_env
  assign("data", data, menu_subpage_env)
  assign("geo_labels", geo_labels, menu_subpage_env)
  assign("colors_palette", colors_palette, menu_subpage_env)
  assign("bar_chart_colors_palette", bar_chart_colors_palette, menu_subpage_env)
  assign("menu_subpage_data", menu_subpage_data, menu_subpage_env)
  assign("menu_category", menu_categories[i], menu_subpage_env)
  assign("menu_category_i", i, menu_subpage_env)
  assign("pdf_reports", pdf_reports, menu_subpage_env)
  
  # Knit menu_subpage.RMD using the menu_subpage_env and add result to out vector
  out = c(out, knitr::knit_child(subpage, envir = menu_subpage_env))
}
```

`r paste(knitr::knit_child(text = out), collapse = '')`
